In [1]:
import numpy as np

a = np.zeros(6, dtype = int)
print(a)

[0 0 0 0 0 0]


In [2]:
a = np.ones(6, dtype = int)
print(a)

[1 1 1 1 1 1]


In [3]:
a = np.ones(6, dtype = int)
print(a*5)

[5 5 5 5 5 5]


In [4]:
array=np.arange(1,99,1)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98]


In [5]:
array=np.arange(1,99,2)
print(array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]


In [8]:
x =  np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [9]:
x =  np.array([[9, 10, 11], [12, 13, 14],[15, 16, 17]])
print(x)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [10]:
x = np.identity(4, dtype = int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
from numpy import random

x = random.rand(1)
print(x)

[0.34012005]


In [13]:
x = np.linspace(0, 1, 10)
print(x)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [14]:
a = np.array([[1, 1], [2, 2]])
b = np.array([[1, 1], [2, 2]])
equal_arrays = (a == b).all()
print(equal_arrays)

True


In [15]:
a = np.zeros(20)
a[6] = 5
print(a)

[0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
a = np.arange(1,100)
a = a[::-1]
print(a)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


In [20]:
x = np.arange(400).reshape(20,20)
print(x)

max_x = np.max(x)
min_x = np.min(x)

print("Max: ",max_x)
print("Min: ",min_x)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219]
 [220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235

In [21]:
x=random.randint(100, size=(50))
a = np.mean(x)
print(a)

52.22


In [23]:
a = np.ones((20,20))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [24]:
a = np.empty((10,10))
a[:] = np.nan
print(a)

[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


In [30]:
a = np.diag([9,8,7],-1)
print (a)

[[0 0 0 0]
 [9 0 0 0]
 [0 8 0 0]
 [0 0 7 0]]


In [31]:
x = np.zeros ((16,16), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [33]:
dt = np.dtype(np.int32)
print(dt)
dx = np.dtype(np.float64)
print(dx)

int32
float64


In [35]:
import pandas as pd

l = ['H','E','L','L','O']
s = pd.Series(l)
print(s)

dt = {'H':1,'E':7,'L':2,'L':5,'O':3,}
x = pd.Series(dt)
print(x)

0    H
1    E
2    L
3    L
4    O
dtype: object
H    1
E    7
L    5
O    3
dtype: int64


In [37]:
a = pd.Series(np.linspace(1, 10, 5))
print(a)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64


In [39]:
dt = pd.Series({97:'a', 98:'b', 99:'c', 100:'d', 101:'e', 102:'f'})

index = dt.index
values = dt.values

print(index)
print(values)

Int64Index([97, 98, 99, 100, 101, 102], dtype='int64')
['a' 'b' 'c' 'd' 'e' 'f']


In [42]:
dt = {'H':1,'E':7,'L':2,'L':5,'O':3,}
x = pd.Series(dt)
print(x)
print(len(x))
print(x.shape)
print(x.size)

H    1
E    7
L    5
O    3
dtype: int64
4
(4,)
4


In [46]:
dt = {'H':1,'E':7,'L':2,'L':5,'O':3,}
x = pd.Series(dt)
print(x.head(2))
print(x.tail(2))

H    1
E    7
dtype: int64
L    5
O    3
dtype: int64


In [49]:
df = pd.DataFrame({'A' :[0, 3, None, 10, 3, None], 'B' : [None, None, 7.13, 13.82, 7, 7], 'C' : [None, "Pandas", None, "Pandas", "Python", "JavaScript"]}) 
print(df)
df.fillna(df.mean(numeric_only=True).round(1), inplace=True)
print(df)

      A      B           C
0   0.0    NaN        None
1   3.0    NaN      Pandas
2   NaN   7.13        None
3  10.0  13.82      Pandas
4   3.0   7.00      Python
5   NaN   7.00  JavaScript
      A      B           C
0   0.0   8.70        None
1   3.0   8.70      Pandas
2   4.0   7.13        None
3  10.0  13.82      Pandas
4   3.0   7.00      Python
5   4.0   7.00  JavaScript


In [51]:
print(df)
df.duplicated()

      A      B           C
0   0.0   8.70        None
1   3.0   8.70      Pandas
2   4.0   7.13        None
3  10.0  13.82      Pandas
4   3.0   7.00      Python
5   4.0   7.00  JavaScript


0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool